### ISSUE TITLE
Cannot enable BlenderBIMSpreadsheet322.zip after installation 

### ISSUE THREAD

**Issue by Sigmoidas** [C-Claus/BlenderScripts#4]
Blender 3.1.2
BlenderBIM 0.0.220516

I am able to successfully install BlenderBIMSpreadsheet322.zip
Then I close Blender, launch it again, and try to enable the BlenderBIM Spreadsheet 1.0.1 — I get an error.
When I use the aforementioned steps to install and enable BlenderBIMSpreadsheet310.zip I have no issues whatsoever.
The output from Blender System Console is available below:
```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\HP ZBook 15 G2\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\BlenderBIMSpreadsheet.py", line 32, in <module>
    import pandas as pd
  File "C:\Users\HP ZBook 15 G2\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\libs\site\packages\pandas\__init__.py", line 22, in <module>
    from pandas.compat import (
  File "C:\Users\HP ZBook 15 G2\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\libs\site\packages\pandas\compat\__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "C:\Users\HP ZBook 15 G2\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\libs\site\packages\pandas\compat\numpy\__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "C:\Users\HP ZBook 15 G2\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\libs\site\packages\pandas\util\__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "C:\Users\HP ZBook 15 G2\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\libs\site\packages\pandas\util\_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "C:\Users\HP ZBook 15 G2\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\libs\site\packages\pandas\_libs\__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas\_libs\interval.pyx", line 1, in init pandas._libs.interval
  File "pandas\_libs\hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas\_libs\missing.pyx", line 1, in init pandas._libs.missing
  File "C:\Users\HP ZBook 15 G2\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\libs\site\packages\pandas\_libs\tslibs\__init__.py", line 36, in <module>
    from pandas._libs.tslibs.nattype import (
ImportError: cannot import name 'is_null_datetimelike' from 'pandas._libs.tslibs.nattype' (C:\Users\HP ZBook 15 G2\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\libs\site\packages\pandas\_libs\tslibs\nattype.cp310-win_amd64.pyd)
```

**Comment by C-Claus** [comment]
Could you try this version please?

https://github.com/C-Claus/BlenderScripts/tree/master/BlenderBIMSpreadsheet/3.3.3

**Comment by Sigmoidas** [comment]
When I try to install "BlenderBIMSpreadsheet333.zip" nothing happens. 
When I try to install "BlenderBIMSpreadsheet310.zip" it installs without a glitch.

Below is console's chronologic output for both operations:

```
Modules Installed () from 'C:\\Users\\HP ZBook 15 G2\\Sync\\SOLARIX OFFICE\\0_STUDIO\\0_standard documents\\Computerprogrammas\\Blender\\Add-ons\\BlenderBIMSpreadsheet\\BlenderBIMSpreadsheet333.zip' into 'C:\\Users\\HP ZBook 15 G2\\AppData\\Roaming\\Blender Foundation\\Blender\\3.1\\scripts\\addons'
addon_utils.disable: BlenderBIMSpreadsheet not disabled
Modules Installed (BlenderBIMSpreadsheet) from 'C:\\Users\\HP ZBook 15 G2\\Sync\\SOLARIX OFFICE\\0_STUDIO\\0_standard documents\\Computerprogrammas\\Blender\\Add-ons\\BlenderBIMSpreadsheet\\BlenderBIMSpreadsheet310.zip' into 'C:\\Users\\HP ZBook 15 G2\\AppData\\Roaming\\Blender Foundation\\Blender\\3.1\\scripts\\addons'
```

**Comment by C-Claus** [comment]
Do you have Blender 3.3.3 installed? With Windows you should start Blender with Admin rights.

**Comment by Sigmoidas** [comment]
> Do you have Blender 3.3.3 installed? With Windows you should start Blender with Admin rights.

I am using Blender 3.1.2

Will check it with Blender 3.3.3 later today, tomorow.

**Comment by Sigmoidas** [comment]
I have installed the latest stable Blender version — 3.3.0. 
Launched Blender with Administrator rights. 
The same issue as before.

Tried installing "BlenderBIMSpreadsheet333.zip" and failed.
Installed "BlenderBIMSpreadsheet310.zip" without a glitch.
Enabled "BlenderBIMSpreadsheet310.zip" in the "Add-ons".

Chronologic Console output below:
```
Modules Installed () from 'C:\\Users\\HP ZBook 15 G2\\Sync\\SOLARIX OFFICE\\0_STUDIO\\0_standard documents\\Computerprogrammas\\Blender\\Add-ons\\BlenderBIMSpreadsheet\\BlenderBIMSpreadsheet333.zip' into 'C:\\Users\\HP ZBook 15 G2\\AppData\\Roaming\\Blender Foundation\\Blender\\3.3\\scripts\\addons'
addon_utils.disable: BlenderBIMSpreadsheet not disabled
Modules Installed (BlenderBIMSpreadsheet) from 'C:\\Users\\HP ZBook 15 G2\\Sync\\SOLARIX OFFICE\\0_STUDIO\\0_standard documents\\Computerprogrammas\\Blender\\Add-ons\\BlenderBIMSpreadsheet\\BlenderBIMSpreadsheet310.zip' into 'C:\\Users\\HP ZBook 15 G2\\AppData\\Roaming\\Blender Foundation\\Blender\\3.3\\scripts\\addons'
openpyxl 3.0.9 C:\Users\HP ZBook 15 G2\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\libs\site\packages\openpyxl\__init__.py
pandas 1.4.1 C:\Users\HP ZBook 15 G2\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\libs\site\packages\pandas\__init__.py
xlsxwriter 1.2.9 C:\Users\HP ZBook 15 G2\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\libs\site\packages\xlsxwriter\__init__.py 
```

**Comment by C-Claus** [comment]
I am lost, maybe you should try removing BlenderBIMSpreadsheet310 completely?

**Comment by Sigmoidas** [comment]
> I am lost, maybe you should try removing BlenderBIMSpreadsheet310 completely?

I remove BlenderBIMSpreadsheet310 from Blender.
Close Blender and relaunch it with Administrator rights.
Then try to install "BlenderBIMSpreadsheet333.zip".

Should I also try to remove some  BlenderBIMSpreadsheet310 files from some Blender directory?
Could there be some other Add-on that's causing this bug?

I will try it later on another PC with a fresh Blender 3.3.0 install.

**Comment by C-Claus** [comment]
So it worked? I think 310 and 330 are conflicting somehow. Don't know yet why.

**Comment by Sigmoidas** [comment]
> So it worked? I think 310 and 330 are conflicting somehow. Don't know yet why.

"BlenderBIMSpreadsheet333.zip" does not install on the current PC running Blender 3.3.0

**Comment by Sigmoidas** [comment]
Blender 3.3.0
BlenderBIM 0.0.220516

I have installed "BlenderBIMSpreadsheet333.zip" on my home PC without any issues. 
It was a clean Blender install.
I guess I will try a clean Blender install on the work PC too.

**Comment by Sigmoidas** [comment]
On my work PV, I have uninstalled Blender, and deleted all files from:
C:\Program Files\Blender Foundation\blender\[version]\addons
C:\Users\[profile]\AppData\Roaming\Blender Foundation\...  

Then reinstalled:
Blender 3.3.0
BlenderBIM 0.0.220516

Still not able to install "BlenderBIMSpreadsheet333.zip".

"BlenderBIMSpreadsheet310.zip" works fine though.

**Comment by C-Claus** [comment]
Could you try again please? I have updated the BlenderBIMSpreadsheet333.zip

**Comment by Sigmoidas** [comment]
BlenderBIMSpreadsheet333.zip installs, enables, and functions flawlessly.

Blender 3.3.0
BlenderBIM 0.0.220516
