### ISSUE TITLE
Blender 3.4 sheets cant enable

### ISSUE THREAD

**Issue by stefan-STMODE** [C-Claus/BlenderScripts#6]
Hi C-Claus i get errors on version 3.4 when i enable it.

**Comment by stefan-STMODE** [comment]
![blender 3 4 error](https://user-images.githubusercontent.com/48913503/214252413-8d02dd43-d3b7-4873-8bea-ba99a44480d9.png)

**Comment by C-Claus** [comment]
Could you verfiy this .zip file works on your end please?

https://github.com/C-Claus/BlenderScripts/blob/master/BlenderBIMSpreadsheet/3.4.1/BlenderBIMSpreadsheet341.zip

**Comment by stefan-STMODE** [comment]
i installed it, and now i can enable it, i also created xlsx document, thank u for the fast fix
